"""empty message

Revision ID: f44569b62b33
Revises: e9add2803e27
Create Date: 2020-02-24 17:24:50.737970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44569b62b33'
down_revision = 'e9add2803e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
